version: '3'

services:
  database:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    # Todo: change to AC2 image from docker hub
    image: lelesd2m2s10/praticando-api
    environment:
      DB_HOST: database
    ports:
      - "9090:9090"
    depends_on:
      - database

volumes:
  db-volume:
